name: Release (Private Packages)
on:
  push:
    branches:
      - master
    paths:
      - ".changeset/**"
      - ".github/workflows/packages-release.yml"
  workflow_dispatch:
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: 'Production - Private Packages'
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 6.14.5  # Specify the pnpm version here
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: setup pnpm store config
        run: ~/.pnpm/pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: verify pnpm-lock.yaml presence
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "Error: pnpm-lock.yaml not found!"
            exit 1
          fi
      - name: install dependencies
        run: ~/.pnpm/pnpm install --frozen-lockfile
