name: Composite Action Example
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: mahalakshmi-rekadi/setup-python-test@main
      - name: Debug File Paths
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          find $GITHUB_WORKSPACE -type f
     
